apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /OSE_wordpress
    server: workstation.lab.example.com
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: claim-wp

