apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /OSE_wordpress
    server: localhost
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: wp-pvc

