apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /OSE_mysql
    server: registry.lab.example.com
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: claim-mysql
